In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4])
print(arr1)

[1 2 3 4]


In [3]:
print(np.__version__)

1.19.5


In [4]:
print(type(arr1))

<class 'numpy.ndarray'>


In [5]:
arr2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [6]:
arr3 = np.array([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9],[10, 11, 12]]])
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [7]:
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
3


In [8]:
print(arr1[3])
print(arr1[2] + arr1[3])

4
7


In [9]:
print(arr2[1, 2])

8


In [10]:
print(arr3[1, 1, 0])

10


In [11]:
b = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(b[:5])
print(b[5:])
print(b[1:7])
print(b[-4:-1])
print(b[2:4:2])
print(b[::3])

[1 2 3 4 5]
[6 7 8 9]
[2 3 4 5 6 7]
[6 7 8]
[3]
[1 4 7]


In [12]:
print(arr2[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [13]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [14]:
arr = np.array([3, 4, 2, 0, 1, 5])
print(np.sort(arr))

[0 1 2 3 4 5]


In [15]:
a = [1, 2, 3, 4]
b = [4, 5, 6, 7]
c = np.add(a, b)

print(c)


[ 5  7  9 11]


In [16]:
import pandas as pd


In [17]:
data = np.array([['','a','b'],
               ['a',1,3],
               ['b',4,8]])
print(pd.DataFrame(data=data[1:,1:],index=data[1:,0],columns=data[0,1:]))

   a  b
a  1  3
b  4  8


In [18]:
import numpy as np
arr = np.array([6, 7, 8, 9])
c = np.searchsorted(arr, 8)
print(c)

2
